registry:
  restart: always
  image: registry:2.2.1
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ./registry/docker_registry:/var/lib/registry
    - ./registry/certs:/certs:ro
    - ./registry/auth:/auth:ro
  ports:
   - 5000
     
registry2:
  restart: always
  image: registry:2.2.1
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - ./registry/docker_registry:/var/lib/registry
    - ./registry/certs:/certs:ro
    - ./registry/auth:/auth:ro
  ports:
   - 5000
     
registry-frontend:
  restart: always
  image: konradkleine/docker-registry-frontend:v2 
  links: 
   - registry:registry
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry  
    ENV_DOCKER_REGISTRY_PORT: 5000 
    ENV_MODE_BROWSE_ONLY: 'false'
    ENV_DOCKER_REGISTRY_USE_SSL: '1'
    ENV_USE_SSL: 'yes'
  volumes:
    - ./registry/certs/domain.crt:/etc/apache2/server.crt:ro
    - ./registry/certs/domain.key:/etc/apache2/server.key:ro
  ports:
   - 8080:80
   - 8443:443


nginx:
  restart: always
  image: nginx:1.9.9
  links:
   - registry:registry
   - registry2:registry2
   - registry-frontend:registry-frontend
  volumes:
    - ./registry/certs/domain.crt:/etc/nginx/ssl/domain.crt:ro
    - ./registry/certs/domain.key:/etc/nginx/ssl/domain.key:ro
    - ./registry/auth/htpasswd:/opt/nginx/conf/.htpasswd:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
   - 80:80
   - 443:443

mirror:
  restart: always
  image: registry:2.2.1
  volumes:
    - ./mirror:/var/lib/registry
  environment:
    STANDALONE: 'false'
    MIRROR_SOURCE: https://registry-1.docker.io
    MIRROR_SOURCE_INDEX: https://index.docker.io registry
  ports:
   - 5555:5000
