registry:
  restart: always
  image: registry:2.1
  net: host
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#    REGISTRY_AUTH: htpasswd
#    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /registry/docker_registry:/var/lib/registry
    - /registry/certs:/certs:ro
    - /registry/auth:/auth:ro
  ports:
   - 5000:5000
     
registry-frontend:
  restart: always
  image: konradkleine/docker-registry-frontend:v2
  net: host
  environment:
    ENV_DOCKER_REGISTRY_HOST: 192.168.1.173 
    ENV_DOCKER_REGISTRY_PORT: 5000 
    ENV_MODE_BROWSE_ONLY: 'false'
    ENV_DOCKER_REGISTRY_USE_SSL: '1'
    ENV_USE_SSL: 'yes'
  volumes:
    - /registry/certs/domain.crt:/etc/apache2/server.crt:ro
    - /registry/certs/domain.key:/etc/apache2/server.key:ro
  ports:
   - 80:80
   - 443:443
